version: '1.0'

services:
  postgres:
    image: postgres:16.3
    ports:
      - 5444:5432
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    env_file:
      - .env

  graphql-engine:
    image: hasura/graphql-engine:v2.40.3
    restart: always
    ports:
      - 9999:8080
    env_file:
      - .env
    depends_on:
      - postgres
