name: Render Deploy WebApp

on:
  push:
    branches:
      - main
    paths:
      - 'services/webapp/**'

jobs:
  deploy-webapp:
    runs-on: ubuntu-latest
    environment: alona-prod
    steps:
      - name: Render Deploy WebApp
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_WEBAPP_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}